[tool.commitizen]
name = "cz_gitmoji"
tag_format = "$version"
version_scheme = "semver"
version_provider = "scm"
update_changelog_on_bump = true
version_files = [
	"CHANGELOG.md:^## v"
]
bump_message = "ðŸ”– bump(release): $current_version â†’ $new_version"
