services:
  docs:
    image: squidfunk/mkdocs-material:latest
    container_name: fintech-docs
    ports:
      - "8000:8000"
    volumes:
      - .:/docs
    working_dir: /docs
    entrypoint: ["/bin/sh", "-lc"]
    command:
      - pip install --no-cache-dir mkdocs-swagger-ui-tag && mkdocs serve -a 0.0.0.0:8000
