name: Bump version

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'ðŸ”– bump(release):')"
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN || github.token }}
          fetch-depth: 0
          fetch-tags: true

      - name: Fetch tags
        run: git fetch --force --tags

      - name: Create bump and changelog
        id: cz
        uses: commitizen-tools/commitizen-action@bb4f1df6601e2a1a891506581b0c53acdc88e07d # 0.26.0
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN || github.token }}
          commitizen_version: "4.10.1"
          changelog_increment_filename: body.md
          extra_requirements: cz-conventional-gitmoji

      - name: Release
        if: steps.cz.outputs.version != steps.cz.outputs.previous_version
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          body_path: body.md
          tag_name: v${{ steps.cz.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
